title: Shivakumar Ravichandran
logo: /assets/img/logo.png
description: Holding 8 Years of experience in IT and skilled in AWS, Python.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
